global:
  checkNewVersion: false
  sendAnonymousUsage: false
#serversTransport:
#  insecureSkipVerify: true
entryPoints:
  web:
    address: ":8081"
  websecure:
    address: ":8443"
providers:
  file:
    directory: /etc/traefik/dynamic.d
    watch: true
  docker:
    exposedByDefault: false
    endpoint: "tcp://docker-socket-proxy:2375"
    network: "traefik"
log:
  level: info
accessLog: {}
certificatesResolvers:
  le-staging:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: your-email@example.com
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web
