http:
  middlewares:
    ipwhitelist-private:
      ipWhiteList:
        sourceRange:
          - "127.0.0.1/32"
    redirect-to-https:
      redirectScheme:
        scheme: "https"
    hsts-headers:
      headers:
        stsSeconds: "15552000"
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
